### ISSUE TITLE
Establish data collection method

### ISSUE THREAD

**Issue by zaidi-01** [zaidi-01/PantryPal#3]

**Comment by AliZaidi1500** [comment]
Made a decision to go with data gathered in the [openrecipes](https://github.com/fictivekin/openrecipes) repository.

**Comment by AliZaidi1500** [comment]
Reopening to spend some more time looking for another data source. [openrecipes](https://github.com/fictivekin/openrecipes) lacks instructions and nutritional information.

**Comment by StevieShibly8** [comment]
Made a decision to go with data gathered in the [allrecipes-scraper](https://github.com/shaansubbaiah/allrecipes-scraper/blob/main/export/scraped-07-05-21.csv) repository
