### ISSUE TITLE
Gather recipe data

### ISSUE THREAD

**Issue by zaidi-01** [zaidi-01/PantryPal#5]
Convert the recipe data found in #3, from JSON to SQL queries. The data follows https://schema.org/Recipe standard.

- [x] #3

**Comment by StevieShibly8** [comment]
Recipe data gathered from https://github.com/shaansubbaiah/allrecipes-scraper/blob/main/export/scraped-07-05-21.csv
Ingredient data gathered from https://world.openfoodfacts.org/ingredients.json
Dataset converted to SQL queries and stored into database
